[tools]
bun = "1.3.3"
poetry = "2.2.1"
python = "3.14.0"

[tasks."client:install"]
dir = "client"
run = "bun install"

[tasks."server:install"]
dir = "server"
run = "poetry install"

[tasks."server:env"]
dir = "server"
run = "$(poetry env activate)"
